version: 2.1
parameters:
  run_integration_tests:
    type: boolean
    default: true
  build:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: true

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - build_job
      - deploy_job
          #requires:
          #  - build_job

jobs:
  build_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - when:
          condition: << pipeline.parameters.build >>
          steps:
            - run: echo "Building"
            
  deploy_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - when:
          condition: << pipeline.parameters.deploy >>
          steps:
            - run: echo "Deploying"