version: 2.1
parameters:
  run_integration_tests:
    type: boolean
    default: true
  hold_deploy_flag:
    type: boolean
    default: true

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - build_job:
          filters:
            branches:
              only: master
            tags:
              only: with_approval
          
      - download_artifact_job:
          requires: 
            - build_job
          filters:
            branches:
              only: master
            tags:
              only: with_approval

      - hold_deploy_1:
          type: approval
          requires: 
            - download_artifact_job
          filters:
            branches:
              ignore: master
            tags:
              only: with_approval

      - hold_deploy_2:
          type: approval
          requires: 
            - download_artifact_job
          filters:
            branches:
              ignore: master
            tags:
              only: with_approval

      - hold_deploy_3:
          type: approval
          requires: 
            - download_artifact_job
          filters:
            branches:
              ignore: master
            tags:
              only: with_approval

      - deploy_job:
          name: Deploy server 1
          requires:
            - download_artifact_job
            - hold_deploy_1
          filters:
            branches:
              only: master
            tags:
              only: with_approval

      - deploy_job:
          name: Deploy server 2
          requires:
            - download_artifact_job
            - hold_deploy_2
          filters:
            branches:
              only: master
            tags:
              only: with_approval

      - deploy_job:
          name: Deploy server 3
          requires:
            - download_artifact_job
            - hold_deploy_3
          filters:
            branches:
              only: master
            tags:
              only: with_approval

jobs:
  build_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: echo "Building"
      - when:
          condition: << pipeline.parameters.hold_deploy_flag >>
          steps:
            - run: echo "Conditional Building step"
            #- hold_deploy
            
    
  download_artifact_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: echo "Downloading artifact"

  deploy_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      #- when:
      #    condition: << pipeline.parameters.hold_deploy_flag >>
      #    steps:
      #      - hold_deploy
      - checkout
      - run: echo "Deploying"
