version: 2.1
parameters:
  run_integration_tests:
    type: boolean
    default: true
  hold_deploy_flag:
    type: boolean
    default: true

workflows:
  version: 2
  integration_tests:
    when: << pipeline.parameters.run_integration_tests >>
    jobs:
      - build_job
      - hold_deploy:
          type: approval
          requires: 
            - build_job
          filters:
            branches:
              ignore: master
              #only: master
      - deploy_job:
          requires:
            - build_job
            - hold_deploy

jobs:
  build_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - run: echo "Building"
      - when:
          condition: << pipeline.parameters.hold_deploy_flag >>
          steps:
            - run: echo "Conditional Building step"
            #- hold_deploy
            
    
  deploy_job:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      #- when:
      #    condition: << pipeline.parameters.hold_deploy_flag >>
      #    steps:
      #      - hold_deploy
      - checkout
      - run: echo "Deploying"
